# Generated by Django 4.2.1 on 2023-08-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Adventure', 'Adventure'), ('Computer Science', 'Computer Science'), ('Poetry', 'Poetry'), ('Religious', 'Religious'), ('Novel', 'Novel'), ('Drama', 'Drama'), ('Sci-Fi', 'Sci-Fi'), ('Comedy', 'Comedy'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Humor', 'Humor'), ('Mystery', 'Mystery')], max_length=30)),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('last_pub', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
