# Generated by Django 4.2.1 on 2023-08-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbook',
            old_name='book_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='addbook',
            name='isbn',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='addbook',
            name='no_of_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='category',
            field=models.CharField(choices=[('Humor', 'Humor'), ('Comedy', 'Comedy'), ('Poetry', 'Poetry'), ('Computer Science', 'Computer Science'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('Adventure', 'Adventure'), ('Horror', 'Horror'), ('Novel', 'Novel'), ('Drama', 'Drama'), ('Religious', 'Religious'), ('Mystery', 'Mystery')], max_length=30),
        ),
    ]
