# Generated by Django 4.2.1 on 2023-08-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_book_name_addbook_title_addbook_isbn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Thriller', 'Thriller'), ('Drama', 'Drama'), ('Humor', 'Humor'), ('Adventure', 'Adventure'), ('Sci-Fi', 'Sci-Fi'), ('Religious', 'Religious'), ('Mystery', 'Mystery'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Poetry', 'Poetry'), ('Novel', 'Novel')], max_length=30)),
                ('isbn', models.CharField(default='null', max_length=64)),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('last_pub', models.DateTimeField(auto_now=True)),
                ('no_of_books', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='AddBook',
        ),
    ]
